[package]
name = "dungeon-crawler-model"
version = "0.1.0"
authors = ["nystromjd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_derive = "1"
